### ISSUE TITLE
"Date" facet does not display after performing an advanced search in arch

### ISSUE THREAD

**Issue by nikdragovic** [emory-libraries/dlp-lux#273] opened 2020-02-03 13:54 UTC
I tested this using "african" in Subject - Topics. It appears to occur for all sort options.

**Comment by wulman16** [comment] 2020-02-05 16:10
After some more investigation, it looks like performing any non-blank search in arch results in the date facet disappearing. This happens in both simple search and advanced search. I cannot reproduce this bug in prod, in test (which is currently running the same version as arch), or locally.

**Comment by wulman16** [comment] 2020-02-05 21:20
It appears that objects in digital-arch don't have the `:year_for_lux` field indexed in Solr (unlike digital-test). I kicked off a re-index job in curate-arch, so we'll see if that fixes the problem.

**Comment by wulman16** [comment] 2020-02-07 19:11
This ticket is blocked by a ticket in Curate: https://github.com/emory-libraries/dlp-curate/issues/963

**Comment by tmiles2** [comment] 2020-02-11 14:32
@wulman16 @rotated8 are we moving this back to the backlog like we discussed in standup yesterday?

**Comment by wulman16** [comment] 2020-02-11 15:29
@tmiles2 I remember discussing whether the ticket in Curate blocking this ticket was being prioritized or not. The Curate ticket is now in Queued, but I don't know if we came to a decision on where to put this one.

**Comment by nikdragovic** [comment] 2020-02-11 15:30
@wulman16 I think blocked is a good place but will defer to Tiffany.

**Comment by rotated8** [comment] 2020-02-11 16:37
I'd prefer to have this in blocked.

**Closed** 2020-02-18 19:09 UTC
Labels: bug
