### ISSUE TITLE
Secure Solr and Fedora in all environments, move iiif to internal ALB

### ISSUE THREAD

**Issue by maxkadel** [emory-libraries/dlp-lux#447] opened 2020-03-26 18:20 UTC
In order to make Lux available outside the VPN, and maintain secure Emory Data Assets, both Solr and Fedora need to be restricted to only be available to the applications.

 - Solr
  - [ ] solr-cor-arch
  - [ ] solr-cor-test
  - [ ] solr-cor
 - Fedora
  - [x] arch
  - [x] test
  - [x] prod
  - [ ] Change the Fedora Password
- IIIF
- [x] Move the iiif's to the internal-only ALB. There is no need for it to be on the public VIP ALB since it's being proxied through curate

**Comment by SolomonHD** [comment] 2020-03-27 00:32
Current plan is to make solr and fedora's http accessable only to curate. If a developer needs access to the admin page of solr or fedora's rest api, you'll have to tunnel an SSH connection to localhost. I plan on completing this after demo tomorrow.

**Comment by SolomonHD** [comment] 2020-03-31 19:03
I've tested moving iiif-cor-arch's DNS to the internal only ALB. Everything seems to be working fine with curate and digital arch. I will submit another ticket moving iiif-cor-test and iiif-cor.

**Comment by SolomonHD** [comment] 2020-04-06 18:03
We're still pending the reindex job on Curate Prod

**Comment by maxkadel** [comment] 2020-04-07 18:23
Current status as of 4/7/2020

* Production
  * [Fedora](http://fedora-cor.library.emory.edu/fcrepo/rest/prod) - not secured (accessed on VPN) 
  * [Solr](http://solr-cor.library.emory.edu/solr/) - not secured (accessed on VPN)
  * [Cantaloupe](https://iiif-cor.library.emory.edu/cantaloupe/iiif/2/84596eea4051200f04a583f02b5999274ff40696/full/500,/0/default.jpg) - not secured (accessed on VPN)
* Test
  * [Fedora](http://fedora-cor-test.library.emory.edu/fcrepo/rest/prod) - not secured (accessed on VPN) 
  * [Solr](http://solr-cor-test.library.emory.edu/solr/) - not secured (accessed on VPN)
  * [Cantaloupe](https://iiif-cor-test.library.emory.edu/cantaloupe/iiif/2/8493a9aa20749c7320b1c76a96570a6e31c07122/full/274,/0/default.jpg) - not secured (accessed on VPN)
* Arch
  * [Fedora](http://fedora-cor-arch.library.emory.edu/fcrepo/rest/prod) - not secured (accessed on VPN) 
  * [Solr](http://solr-cor-arch.library.emory.edu/solr/) - not secured (accessed on VPN)
  * [Cantaloupe](https://iiif-cor-arch.library.emory.edu/cantaloupe/iiif/2/ead71d7a280cd5a772a39b2acfd61be4bb11e103/full/90,/0/default.jpg?t=1586283764833) - not secured (accessed on VPN)

**Comment by eporter23** [comment] 2020-04-08 20:00
An update on this after our team discussion on 4/8. Kathryn is a member of our team who uses VPN to connect to Curate, Lux currently, but does not have elevated VPN core or AWS access. I asked her to try to connect to our SOLR and Fedora URLs while connected via VPN, and she is unable to reach them. Screenshot: ![Capture.JPG](https://images.zenhubusercontent.com/5b6de3fda32a4f476097b0be/5835ac0e-4d8d-4a28-81f8-ae21ec144783)

**Comment by tmiles2** [comment] 2020-04-09 18:05
@eporter23 Can you confirm that Kathryn can reach digital library as expected?

**Comment by eporter23** [comment] 2020-04-09 18:49
@tmiles2 I just confirmed this.

**Comment by SolomonHD** [comment] 2020-04-13 18:59
Closing the ticket because solr/fedora/iiif is behind VPN elevated access. We will create another ticket for proposed further hardening.

**Closed by SolomonHD** 2020-04-13 18:59 UTC
Labels: Middleware
